### ISSUE TITLE
Kameras aus OSM

### ISSUE THREAD

**Issue by Matthias84** [Jugendhackt/NoCam#1]
Hi, vielleicht kennt ihr ja die freie Karte www.openstreetmap.org, wo es auch die Rohdaten unter einer freien Lizenz gibt. Auch für Kameras gibt es [ein Datenmodell](https://wiki.openstreetmap.org/wiki/Key:surveillance), was man zum Beispiel [hier](http://overpass-turbo.eu/s/c9M) filtern und herunterladen kann. Anzuschauen gibts das [hier](http://osmcamera.tk/).

Wenn ihr euer Dateiformat auf [geoJSON](http://geojson.org/) umstellt, könnt ihr nicht nur diese neue Quelle nutzen, sondern so ziemlich alles was es so an Quellen für Geodaten gibt :-)

P.S. Sehr schöne Idee das mal so mit gamification zu kreuzen!

**Comment by jugendhacker** [comment]
Ja, aber es ist schwerer einzubinden, deswegen Google Maps (wegen der Zeit).

**Comment by Matthias84** [comment]
Konkret meinte ich das nur als Datenquelle, nicht für die Darstellung. Ich hab ja leider keine Ahnung von Android, aber stimmt, da braucht man dann [zusätzliche Widgets](https://wiki.openstreetmap.org/wiki/Frameworks#Widgets).
